quiz/urls.py
from django.conf.urls import patterns, url

from .views import QuizListView, CategoriesListView,\
    ViewQuizListByCategory, QuizUserProgressView, QuizMarkingList,\
    QuizMarkingDetail, QuizDetailView, QuizTake


urlpatterns = patterns('',

                       url(regex=r'^$',
                           view=QuizListView.as_view(),
                           name='quiz_index'),

                       url(regex=r'^category/$',
                           view=CategoriesListView.as_view(),
                           name='quiz_category_list_all'),

                       url(regex=r'^category/(?P<category_name>[\w.-]+)/$',
                           view=ViewQuizListByCategory.as_view(),
                           name='quiz_category_list_matching'),

                       url(regex=r'^progress/$',
                           view=QuizUserProgressView.as_view(),
                           name='quiz_progress'),

                       url(regex=r'^marking/$',
                           view=QuizMarkingList.as_view(),
                           name='quiz_marking'),

                       url(regex=r'^marking/(?P<pk>[\d.]+)/$',
                           view=QuizMarkingDetail.as_view(),
                           name='quiz_marking_detail'),

                       #  passes variable 'quiz_name' to quiz_take view
                       url(regex=r'^(?P<slug>[\w-]+)/$',
                           view=QuizDetailView.as_view(),
                           name='quiz_start_page'),

                       # url(regex=r'^(?P<quiz_name>[\w-]+)/take/$',
                       #     view=QuizTake.as_view(),
                       #     name='quiz_question'),
)

lessons/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericRelation
from django.utils.text import slugify

from model_utils.models import TimeStampedModel

from quiz.models import Quiz
from discussions.models import Post

CONTENT_TYPES = (
    ('topic', 'Topics'),
    ('media', 'Consider This'),
    ('reading', 'More To Consider'),
    ('quiz', 'Test Yourself'), 
    ('apply', 'Apply'),    
)

class Project(models.Model):
    title = models.CharField(max_length=512)
    description = models.TextField(blank=True)
    slug = models.SlugField(blank=True)
    public = models.BooleanField(default=False)

    def get_lessons(self):
        lessons = []
        modules = self.project_modules.all().order_by('order')
        for mod in modules:
            for lsnmod in mod.lessons.all().order_by('order'):
                lessons.append((mod, lsnmod.lesson))
        return lessons 

    def get_absolute_url(self):
        return reverse('project', args=[str(self.slug)])

    def __unicode__(self):
        return self.title


class Module(models.Model):
    title = models.CharField(max_length=512)
    description = models.TextField(blank=True)
    slug = models.SlugField(blank=True)
    order = models.IntegerField(default=0)
    project = models.ForeignKey(Project, related_name='project_modules')

    def save(self, *args, **kwargs):
        self.slug = slugify(unicode(self.title))
        super(Module, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        try:
            lessons = self.lessons.all()
            for i in lessons:
                i.delete()
            
        except Exception as e:
            pass  # proceed silently
            
        super(Module, self).delete(*args, **kwargs) # Call the "real" delete() 

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('module', args=[self.project.slug, self.id])

    class Meta:
        ordering = ['order']


class Lesson(TimeStampedModel):
    title = models.CharField(max_length=512)
    description = models.TextField(blank=True)
    slug = models.SlugField(blank=True)
    # module = models.ForeignKey(Module, related_name='lessons')
    active = models.BooleanField(default=True)
    # order = models.IntegerField(default=0)
    creator = models.ForeignKey(User, null=True)

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('lesson_permlink', args=[str(self.id)])

    def save(self, *args, **kwargs):
        self.slug = slugify(unicode(self.title))
        self.slug = self.slug[:49]
        super(Lesson, self).save(*args, **kwargs)

        if not self.sections.all():
            section = LessonSection(content_type='topic', lesson=self)
            section.save()
            section = LessonSection(content_type='media', lesson=self)
            section.save()
            section = LessonSection(content_type='reading', lesson=self)
            section.save()
            section = LessonSection(content_type='apply', lesson=self)
            section.save()

        if not self.lesson_discussion.all():
            try:
                user = self.creator
            except:
                user = User.objects.filter(is_superuser=True)[0]
            try:
                thread = Post(text="Start a discussion!", creator=user, subject=self.title+' Talk', parent_post=None)
                thread.save()
                discussion = LessonDiscussion(thread=thread, lesson=self)
                discussion.save()
            except:
                pass  # Fail silently...

        if not self.lesson_quiz.all():
            
            try:
                title = '%s Quiz'% (self.title)
                quiz = Quiz(title=title, url=title, random_order=False, answers_at_end=True)
                quiz.save()
                lesson_quiz = LessonQuiz(quiz=quiz, lesson=self)
                lesson_quiz.save()
            except Exception as e:
                pass  # Fail silently...

    def delete(self, *args, **kwargs):
        try:
            q = self.lesson_quiz.all().get()
            q.quiz.delete()
            d = self.lesson_discussion.all().get()
            d.thread.delete()
        except Exception as e:
            pass  # proceed silently
            
        super(Lesson, self).delete(*args, **kwargs) # Call the "real" delete() 


class LessonModule(models.Model):
    module = models.ForeignKey(Module, related_name='lessons')
    lesson = models.ForeignKey(Lesson, related_name='modules')
    order = models.IntegerField(default=0)

    class Meta:
        unique_together = (('module', 'lesson'),)
        ordering = ['order']
    

class LessonSection(models.Model):
    text = models.TextField(default='Coming soon...')
    content_type = models.CharField(max_length=64, choices=CONTENT_TYPES, default='text')
    lesson = models.ForeignKey(Lesson, related_name='sections')
    
    def __unicode__(self):
        return '%s' % (self.content_type)

    def get_absolute_url(self):
        return reverse('lesson_section_permlink', args=[str(self.lesson.id), str(self.content_type)])


class LessonQuiz(models.Model):
    quiz = models.ForeignKey(Quiz, related_name='lesson')
    lesson = models.ForeignKey(Lesson, related_name='lesson_quiz')

    class Meta:
        verbose_name = 'Lesson / Quiz Pair'

    # def delete(self, *args, **kwargs):
    #     try:
    #         self.quiz.delete()
    #         self.lesson.delete()
    #     except:
    #         pass  # proceed silently

    #     super(LessonQuiz, self).delete(*args, **kwargs) # Call the "real" delete() 
    
    def __unicode__(self):
        return '%s --> %s' % (self.lesson, self.quiz)


class LessonDiscussion(models.Model):
    thread = models.ForeignKey(Post, related_name='lesson_post')
    lesson = models.ForeignKey(Lesson, related_name='lesson_discussion')

    class Meta:
        verbose_name = 'Lesson / Discussion Pair'
        unique_together = (('thread', 'lesson'),)

    def __unicode__(self):
        return '%s --> %s' % (self.lesson, self.thread)


class PbllPage(models.Model):
    title = models.CharField(max_length=512)
    content = models.TextField(blank=True)
    slug = models.SlugField(blank=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(unicode(self.title))
        super(PbllPage, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('pbllpage', args=[str(self.slug)])

discussions/views.py
from django.views.generic import TemplateView, CreateView, ListView, DetailView, DeleteView, UpdateView, FormView, View
from django.core.urlresolvers import reverse

from braces.views import CsrfExemptMixin, JSONResponseMixin, AjaxResponseMixin, LoginRequiredMixin, StaffuserRequiredMixin

from .models import Post, DiscussionLog
from .forms import PostForm, PostReplyForm
from lessons.models import LessonDiscussion, Project, Module, LessonModule, Lesson
from core.mixins import HonorCodeRequired, WhitelistRequiredMixin


class DiscussionListView(LoginRequiredMixin, TemplateView):
    template_name = 'discussions_index.html'

    def get(self, request, *args, **kwargs):

        return super(DiscussionListView, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(DiscussionListView, self).get_context_data(**kwargs)
        threads = []
        try:
            self.project_context = Project.objects.get(slug=kwargs['project_slug'])
            lessons = self.project_context.get_lessons()
            # headers = Post.objects.filter(parent_post=None).order_by('created')
            headers = [{'module': i[0], 'lesson':  i[1], 'thread': i[1].lesson_discussion.all()[0].thread} for i in lessons]

            # self = Project.objects.get(slug=kwargs['project_slug'])
        except:
            pass

        for hdr in headers:
           
            # try:
            #     lesson = LessonDiscussion.objects.get(thread=hdr).lesson
            # except:
            #     lesson = None

            

            try:
                logger = DiscussionLog.objects.filter(user=self.request.user).get(discussion=hdr['thread'])
                last_visit =  logger.modified     
            except:
                last_visit = self.request.user.last_login
        
            replies = hdr['thread'].replies.all().filter(deleted=False)
            newmsgs = replies.filter(modified__gt = last_visit)            
            threads.append({'module': hdr['module'], 'lesson': hdr['lesson'], 'header': hdr['thread'], 'reply_count': len(replies), 'unread_reply_count': len(newmsgs)})

        context['threads'] = threads
        context['project'] = self.project_context
        return context


class DiscussionView(DetailView):
    model = Post
    template_name = 'discussions.html'
    module_context = None
    project_context = None
    lesson_context = None

    def get(self, request, *args, **kwargs):
        try:
            self.module_context = Module.objects.get(pk=kwargs.get('module_id'))
            self.project_context = self.module_context.project
            self.lesson_context = Lesson.objects.get(pk=kwargs.get('lesson_id'))
        except:
            print kwargs
            pass
        return super(DiscussionView, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(DiscussionView, self).get_context_data(**kwargs)

        context['lesson'] = self.lesson_context
        context['module'] = self.module_context
        context['project'] = self.project_context

        thread_post = self.get_object()
        context['thread'] = thread_post

        try:
            quiz = self.lesson_context.lesson_quiz.get().quiz
            context['quiz'] =  quiz
        except:
            pass
       
        if not self.request.user.is_authenticated():
            return context

        initial_post_data = {}
        initial_post_data['creator'] = self.request.user
        try:
            logger = DiscussionLog.objects.filter(user=self.request.user).get(discussion=thread_post) 
        except:
            logger = DiscussionLog(user=self.request.user, discussion=thread_post)
            logger.save()
        
        replies = thread_post.replies.all().filter(deleted=False).order_by('-created')
        new_replies = replies.filter(modified__gt = logger.modified)

        """ [(post_obj, post_form, [post_replies])]"""
        reply_list = []
        for i in replies:
            thread_reply = (i, i.get_reply_form(creator_init=self.request.user), i.replies.all().filter(deleted=False).order_by('-created'))
            reply_list.append(thread_reply)


        initial_post_data['subject'] = 'Re: %s'% thread_post.subject
        initial_post_data['parent_post'] = thread_post.id  
        form = PostReplyForm(initial=initial_post_data)       

        
        context['thread_list'] = Post.objects.filter(parent_post=None).order_by('created')

        context['replies'] = reply_list
        context['new_replies'] = new_replies
        context['postform'] = form

        logger.save()
        return context


class DiscussionViewPermLink(DetailView):
    model = Post
    template_name = 'discussions_permlink.html'

    def get(self, request, *args, **kwargs):
        return super(DiscussionViewPermLink, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(DiscussionViewPermLink, self).get_context_data(**kwargs)

        initial_post_data = {}
        initial_post_data['creator'] = self.request.user
        thread_post = self.get_object()
        context['thread'] = thread_post

        try:
            lesson = thread_post.lesson_post.all().get().lesson
            context['lesson'] = lesson
        except:
            context['lesson'] = None

        try:
            quiz = lesson.lesson_quiz.get().quiz
            context['quiz'] =  quiz
        except:
            pass

        return context


class PostView(LoginRequiredMixin, ListView):
    model = Post
    template_name = 'post.html'


class PostUpdateView(LoginRequiredMixin, CsrfExemptMixin, UpdateView):
    model = Post
    form_class= PostReplyForm
    template_name = 'edit_form.html'


    def get_form_class(self):
        form_class = super(PostUpdateView, self).get_form_class()
        if self.request.user.is_staff:
            form_class = PostForm
        return form_class

    def get_success_url(self):
        current = self.get_object()
        parent = current.parent_post

        if parent:
            if parent.parent_post:  # subthread. make sure to display master thread
                return reverse('discussion_permlink', args=[str(parent.parent_post.id)])
            return reverse('discussion_permlink', args=[str(parent.id)])
        return reverse('discussion_permlink', args=[str(current.id)])
    

class PostCreateView(LoginRequiredMixin, CsrfExemptMixin, JSONResponseMixin, AjaxResponseMixin, CreateView):
    model = Post
    template_name = 'discussions.html'
    form_class= PostReplyForm


    def post_ajax(self, request, *args, **kwargs):
        postform = PostReplyForm(request.POST)
        if postform.is_valid():

            new_post = postform.save()
            data = {}
            data['id'] = new_post.id
            data['modified'] = new_post.modified.strftime('%b %d %Y %H:%M')
            data['text'] = new_post.text
            data['creator'] = new_post.creator.username
            data['subject'] = new_post.subject

            try:
                logger = DiscussionLog.objects.get(user=request.user, discussion=new_post.parent_post)
                logger.save()
            except:
                pass
            # print self.render_json_response(data)
            return self.render_json_response(data)
        else:
            data = postform.errors
            return self.render_json_response(data)

class PostDeleteView(LoginRequiredMixin, CsrfExemptMixin, JSONResponseMixin, AjaxResponseMixin, View):
   
    def post_ajax(self, request, *args, **kwargs):
        if request:
            try:
                post = Post.objects.get(id=request.POST['post'])
                
                if post.creator == request.user or request.user.is_staff:
                    post.deleted = True
                    post.save()
                    data = 'data removed'
                    return self.render_json_response(data)
                else:
                    data = 'data not removed'

            except Exception as e:
                data = 'data not removed'
        
        return self.render_json_response(data) 

templates/create_form.html
<!-- create_form.html -->
{% extends "base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block content_container %}

<div class="row">
    <div class="col-md-12"><h3>Creating a new {{ object_type }}</h3></div>
    <div class="col-md-10 col-md-offset-1">
    	{{ form.fields.content_type_selected }}
		<form id="basicform" class="" action="" method="post">{% csrf_token %}
			{{ form|crispy }}
			<p><br><input id="update_btn" type="submit" class="btn btn-default" value="Add"/></p>
		</form>
    </div>
</div>
    
{% endblock content_container %}

templates/discussions_index.html
<!-- discussions_index.html -->
{% extends "base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block content_container %}

<div class="row">

    
	<div class="col-md-12"><h1>Discussions</h1></div> 
	{% for i in threads  %}
	
		<div class="col-md-3 col-md-offset-1 well bg-info">
		
			
			<!-- thread header -->
			<a href="{% url 'module' project.slug i.module.id %}">{{ i.module }}</a> / 
			<a href="{% url 'lesson' project.slug i.module.id i.lesson.id %}">{{ i.lesson }}</a>
	    	<small class="" style="float: right"><i>{{ i.reply_count }} replies {% if i.unread_reply_count %} <span class="badge">{{ i.unread_reply_count }}</span> new{% endif %}</i></small>
	    	
	    	
	    	<h4><a href="{% url 'discussion' project.slug i.module.id i.lesson.id i.header.id %}">{{ i.header }}</a><small> by {{ i.header.creator.first_name }}</small></h4>
	           	
		    
		    <!-- thread header text -->
		    <p>{{ i.header.text | truncatewords_html:140 | safe }}</p>
		    
		    <small class="">last activity {{ i.header.modified|date:"M j Y" }} </small>
		    {% if user.is_staff or user == i.header.creator %}<small class="pull-right"> <a href="{% url 'edit_post' i.header.id %}">edit</a>&nbsp; </small>{% endif %}
		
		</div>

	{% endfor %}
	

</div>

{% endblock content_container %}

{% block js_include %}<script src="{% static 'js/discussions.js' %}"></script> {% endblock js_include %}

templates/edit_form.html
<!-- edit_form.html -->
{% extends "base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% load fb_versions %}

{% block content_container %}

<div class="row">
    <div class="col-md-12"><h3>Editing {{ object_type }}: <em>{{ object }}</em> </h3></div>
    <div class="col-md-10 col-md-offset-1">
    	{{ form.fields.content_type_selected }}
		<form id="basicform" class="" action="" method="post">{% csrf_token %}
			{{ form|crispy }}
			<p><input id="update_btn" type="submit" class="btn btn-default" value="Update"/></p>
		</form>
    </div>
</div>

<div class="row">
    {% for i in filelisting %}
        <div class="col-md-12">
                            
        </div>
    {% endfor %}
    
</div>
    
{% endblock content_container %}

templates/inactive.html
<!-- inactive.html -->
{% extends "base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block content_container %}

<div class="row">
    <div class="col-md-8 col-md-offset-2 text-center">
    	{% if user.is_anonymous %}
    	
    		<p>Please <a href="{% url 'social:begin' 'google-oauth2' %}?next={{ request.path }}">sign in</a> before proceeding.</p>

    	{% else %}
            <h2>
                {{ pbllpage.title }}
                {% if user.is_staff %}
                    <a href="{% url 'pbllpage_edit' slug=pbllpage.slug %}" class=""><small><i class="fa fa-pencil"></i></small></a>
                {% endif %}
            </h2>

    		{{ pbllpage.content | safe }}
    	
    	{% endif %}

	<form action="" method="post">{% csrf_token %}
	    {{ form|crispy }}
	    <input type="submit" value="Submit" />
	</form>

    </div>
</div>
    
{% endblock content_container %}

templates/index.html
<!-- index.html -->
{% extends "base.html" %}
{% load staticfiles %}

{% block content_container %}
<div class="row">
	<div class="col-md-12"></div>
	<div class="col-md-12">
		
		{% for i in public_projects %}
			<div class="thumbnail blocks">
				<p class="text-right"><i class="fa fa-unlock fa-1x text-success"></i></p>
				<a href="{{ i.get_absolute_url }}" class="">
					<img src="{% static 'img/nflrc-logo-square.png'%}">
				</a>
				<div class="caption">
					<p><legend> {{ i }} </legend></p>
				</div>				
			</div>
		{% endfor %}
	
		{% for i in member_projects %}
			<div class="thumbnail blocks">
				<p class="text-right">{% if not i.public %} <i class="fa fa-lock fa-1x"></i> {% endif %}</p>
				<a href="{{ i.get_absolute_url }}" class="">
					<img src="{% static 'img/nflrc-logo-square.png'%}">
				</a>
				<div class="caption">
					<p><legend> {{ i }} </legend></p>
				</div>				
			</div>
		{% endfor %}
	</div>
</div>
{% endblock content_container %}

templates/lesson.html
<!-- lesson.html -->
{% extends "base.html" %}
{% load staticfiles %}
{% block series_title %} {% endblock series_title %}

{% block page_header_container %}
	<a href="{% url 'project' project.slug %}" class="static_a_display">{{ project }}</a> • <a href="{{ module.get_absolute_url }}" class="static_a_display">{{ module.title }}</a>	
{% endblock page_header_container %}

{% block content_container %}

<div class="row">
    <div class="col-md-12">
		<span class="lead">{{ lesson }}</span>
		{% if user.is_staff %}
			<a href="{% url 'lesson_edit' lesson.id %}?module={{ module.id }}" class="btn btn-default btn-xs"><i class="fa fa-pencil"></i> edit</a>
			<a href="{% url 'lesson_delete' lesson.id %}?project={{ project.slug }}&module={{ module.id }}" class="btn btn-default btn-xs"><i class="fa fa-minus"></i> remove </a>
		{% endif %}
		
	</div>
    <div class="col-md-9">
		<div class="row">
		{% if not lesson.active and not user.is_staff %}
			<div class="col-md-12">This lesson has not been activated yet.</div>
		{% else %}
			{% for item in section_items %}
				<div class="col-md-12">
			
					<h2>{{ item.get_content_type_display }}
						{% if user.is_staff %}<a href="{% url 'lesson_section_edit' pk=item.id %}?module={{ module.id }}&lesson={{ lesson.id }}" class="btn btn-default btn-xs"><i class="fa fa-pencil"></i> edit</a>{% endif %}
					</h2>
					
					<div>{{ item.text | safe }}</div>
				</div>
			{% endfor %}
		{% endif %}
		</div>
    </div>
    
    <div class="col-md-3">       
	    <div><a href="{% url 'lesson_section' project.slug module.id lesson.id 'topic' %}" class="menu_btn {% if curr_section == 'topic' %}active{% endif %}">Topics</a></div>
	    <div><a href="{% url 'lesson_section' project.slug module.id lesson.id 'media' %}" class="menu_btn {% if curr_section == 'media' %}active{% endif %}">Consider This</a></div>
	    
		{% if quiz %} 
			<div><a href="{% url 'lesson_quiz' project.slug module.id lesson.id quiz.id %}" class="menu_btn ">Test Yourself</a></div>			
		{% endif %} 
		
		<div><a href="{% url 'lesson_section' project.slug module.id lesson.id 'reading' %}" class="menu_btn {% if curr_section == 'reading' %}active{% endif %}">More to Consider</a></div>

		
		{% if lesson_thread %}
			<div><a href="{% url 'discussion' project.slug module.id lesson.id lesson_thread %}" class="menu_btn ">Get Involved</a></div>
				<div class=" reply_preview_list bg-success">
					
					<div style="text-align: left"><small>Latest posting</small></div>
					{% for i in lesson_thread_replies %}
					<a href="{% url 'discussion' project.slug module.id lesson.id lesson_thread %}#post_{{i.id}}">
						<div class="">
							<i class="fa fa-quote-right fa-1x"></i>					
							<div class="reply_preview"><small>{{ i.text|truncatewords:10 | safe }}</small></div>
						</div>
						
					</a>
					<small class="pull-right" alt="{{ i.creator.email }}">{{ i.creator.first_name }}</small>					
					{% empty %}
						<div class=""><small>No recent posts. Be the first!</small></div>
					{% endfor %}
			</div>
		{% endif %}
		
		<div><a href="{% url 'lesson_section' project.slug module.id lesson.id 'apply' %}" class="menu_btn {% if curr_section == 'apply' %}active{% endif %}">Apply</a>	</div>

		<hr>

		<div>
			<a class="menu_btn" href="{% url 'module' project.slug module.id %}">More Lessons <i class="fa fa-caret-right"></i></a>
    	</div>  		
    </div>
</div>
    
{% endblock content_container %}

templates/lesson_module_confirm_delete.html
<!-- generic_confirm_delete.html -->
{% extends "base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block content_container %}
<div class="row ">
    <div class="col-md-4"></div>
    <div class="col-md-4 center-block" style="text-align: center">
        <h3>This will remove lesson {{ object.lesson }} from {{ object.module }} but not the repository.</h3>
        <form action="" method="post">{% csrf_token %}
            <p class="lead">Are you sure you want to do this?</p>
            <input type="submit" value="Remove {{ object.lesson }} from the module but keep in repository" />
            <a href="{{ object.get_absolute_url }}"> Cancel the Request </a>
        </form>
    </div>
    <div class="col-md-4"></div>
</div>
{% endblock content_container %}

templates/lesson_permlink.html
<!-- lesson.html -->
{% extends "base.html" %}
{% load staticfiles %}

{% block content_container %}

<div class="row">
    <div class="col-md-12">
    	<h2>
    		<a href="{{ lesson.module.get_absolute_url }}">{{ lesson.module }}</a> <i class="fa fa-caret-right"></i></a>
    		<span>{{ lesson }}</span>
    		{% if user.is_staff %}<a href="{% url 'lesson_edit' lesson.id %}" class="btn btn-default btn-xs"><i class="fa fa-pencil"></i></a>{% endif %}
    	</h2>
	</div>
    <div class="col-md-9">
		<div class="row">
		{% if not lesson.active and not user.is_staff %}
			<div class="col-md-12">This lesson has not been activated yet.</div>
		{% else %}
			{% for item in section_items %}
				<div class="col-md-12">
			
					<h2>{{ item.get_content_type_display }}
						{% if user.is_staff %}<a href="{% url 'lesson_section_edit' pk=item.id %}" class="btn btn-default btn-xs"><i class="fa fa-pencil"></i></a>{% endif %}
					</h2>
					
					<div>{{ item.text | safe }}</div>
				</div>
			{% endfor %}
		{% endif %}
		</div>
    </div>
    
    <div class="col-md-3">       
	    <div><a href="{% url 'lesson_section_permlink' lesson.id 'topic' %}" class="menu_btn {% if curr_section == 'topic' %}active{% endif %}">Topics</a></div>
	    <div><a href="{% url 'lesson_section_permlink' lesson.id 'media' %}" class="menu_btn {% if curr_section == 'media' %}active{% endif %}">Consider This</a></div>
	    
		{% if quiz %} 
			<div><a href="{% url 'lesson_quiz_permlink' quiz.id %}" class="menu_btn ">Test Yourself</a></div>
			
		{% endif %} 
		
		<div><a href="{% url 'lesson_section_permlink' lesson.id 'reading' %}" class="menu_btn {% if curr_section == 'reading' %}active{% endif %}">More to Consider</a></div>

		
		{% if lesson_thread %}
			<div><a href="{% url 'discussion_permlink' pk=lesson_thread %}" class="menu_btn ">Get Involved</a></div>
			<div class=" reply_preview_list bg-success">
				
				<div style="text-align: left"><small>Latest posting</small></div>
				{% for i in lesson_thread_replies %}
				<a href="{% url 'discussion_permlink' pk=lesson_thread %}#post_{{i.id}}">
					<div class="">
						<i class="fa fa-quote-right fa-1x"></i>					
						<div class="reply_preview"><small>{{ i.text|truncatewords:10 | safe }}</small></div>
					</div>
					
				</a>
				<small class="pull-right" alt="{{ i.creator.email }}">{{ i.creator.first_name }}</small>					
				{% empty %}
					<div class=""><small>No recent posts. Be the first!</small></div>
				{% endfor %}
			</div>
		{% endif %}
		
		<div><a href="{% url 'lesson_section_permlink' lesson.id 'apply' %}" class="menu_btn {% if curr_section == 'apply' %}active{% endif %}">Apply</a>	</div>		
    </div>
</div>
    
{% endblock content_container %}